import type {
  ParkingSpot,
  Visitor,
  Alert,
  Resident,
  User,
  BuildingStats,
  Payment,
  SystemStats,
  Tenant,
  RentalListing,
  MarketplaceProduct,
  Communication,
} from './types'

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'super-1',
    name: 'Carlos Administrador',
    email: 'carlos@resguard.com',
    role: 'super_admin',
  },
  {
    id: 'admin-1',
    name: 'Maria Torres',
    email: 'maria@torresdelparque.com',
    role: 'admin',
    buildingId: 'building-1',
  },
  {
    id: 'admin-2',
    name: 'Pedro Gomez',
    email: 'pedro@residenciasdelsol.com',
    role: 'admin',
    buildingId: 'building-2',
  },
  {
    id: 'vigilante-1',
    name: 'Juan Rodriguez',
    email: 'juan@security.com',
    role: 'vigilante',
    buildingId: 'building-1',
  },
  {
    id: 'vigilante-2',
    name: 'Ana Martinez',
    email: 'ana@security.com',
    role: 'vigilante',
    buildingId: 'building-2',
  },
  {
    id: 'usuario-1',
    name: 'Roberto Mendez',
    email: 'roberto@email.com',
    role: 'usuario',
    buildingId: 'building-1',
  },
  {
    id: 'usuario-2',
    name: 'Elena Torres',
    email: 'elena@email.com',
    role: 'usuario',
    buildingId: 'building-1',
  },
]

// Mock Buildings with Stats
export const mockBuildingStats: BuildingStats[] = [
  {
    id: 'building-1',
    name: 'Torres del Parque',
    address: 'Calle 26 #5-21, Bogota',
    totalUnits: 120,
    occupiedUnits: 115,
    totalParkingSpots: 150,
    visitorParkingSpots: 20,
    activeVisitors: 8,
    pendingAlerts: 3,
    monthlyRevenue: 45000000,
    outstandingBalance: 2500000,
    status: 'active',
    lastPaymentDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    subscriptionStatus: 'active',
  },
  {
    id: 'building-2',
    name: 'Residencias del Sol',
    address: 'Carrera 15 #93-40, Bogota',
    totalUnits: 80,
    occupiedUnits: 78,
    totalParkingSpots: 100,
    visitorParkingSpots: 15,
    activeVisitors: 5,
    pendingAlerts: 1,
    monthlyRevenue: 32000000,
    outstandingBalance: 800000,
    status: 'active',
    lastPaymentDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    subscriptionStatus: 'active',
  },
  {
    id: 'building-3',
    name: 'Mirador de la Sabana',
    address: 'Av. Suba #115-30, Bogota',
    totalUnits: 200,
    occupiedUnits: 185,
    totalParkingSpots: 250,
    visitorParkingSpots: 30,
    activeVisitors: 12,
    pendingAlerts: 7,
    monthlyRevenue: 78000000,
    outstandingBalance: 5200000,
    status: 'active',
    lastPaymentDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    subscriptionStatus: 'active',
  },
  {
    id: 'building-4',
    name: 'Portal del Norte',
    address: 'Calle 170 #45-10, Bogota',
    totalUnits: 60,
    occupiedUnits: 55,
    totalParkingSpots: 70,
    visitorParkingSpots: 10,
    activeVisitors: 2,
    pendingAlerts: 0,
    monthlyRevenue: 22000000,
    outstandingBalance: 0,
    status: 'active',
    lastPaymentDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    subscriptionStatus: 'active',
  },
  {
    id: 'building-5',
    name: 'Conjunto La Esperanza',
    address: 'Carrera 7 #127-50, Bogota',
    totalUnits: 45,
    occupiedUnits: 40,
    totalParkingSpots: 50,
    visitorParkingSpots: 8,
    activeVisitors: 3,
    pendingAlerts: 2,
    monthlyRevenue: 15000000,
    outstandingBalance: 3500000,
    status: 'maintenance',
    lastPaymentDate: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000),
    subscriptionStatus: 'past_due',
  },
]

// Mock Payments
export const mockPayments: Payment[] = [
  {
    id: 'pay-1',
    buildingId: 'building-1',
    buildingName: 'Torres del Parque',
    amount: 450000,
    currency: 'COP',
    status: 'succeeded',
    type: 'subscription',
    description: 'Cuota mensual de administracion - Enero 2026',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'pay-2',
    buildingId: 'building-1',
    buildingName: 'Torres del Parque',
    amount: 15000,
    currency: 'COP',
    status: 'succeeded',
    type: 'overtime_fee',
    description: 'Cargo por tiempo extra de parqueo',
    residentUnit: '502',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'pay-3',
    buildingId: 'building-2',
    buildingName: 'Residencias del Sol',
    amount: 320000,
    currency: 'COP',
    status: 'succeeded',
    type: 'subscription',
    description: 'Cuota mensual de administracion - Enero 2026',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'pay-4',
    buildingId: 'building-3',
    buildingName: 'Mirador de la Sabana',
    amount: 780000,
    currency: 'COP',
    status: 'succeeded',
    type: 'subscription',
    description: 'Cuota mensual de administracion - Enero 2026',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'pay-5',
    buildingId: 'building-5',
    buildingName: 'Conjunto La Esperanza',
    amount: 150000,
    currency: 'COP',
    status: 'failed',
    type: 'subscription',
    description: 'Cuota mensual de administracion - Enero 2026',
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'pay-6',
    buildingId: 'building-1',
    buildingName: 'Torres del Parque',
    amount: 50000,
    currency: 'COP',
    status: 'succeeded',
    type: 'fine',
    description: 'Multa por violacion de norma de ruido',
    residentUnit: '305',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'pay-7',
    buildingId: 'building-2',
    buildingName: 'Residencias del Sol',
    amount: 200000,
    currency: 'COP',
    status: 'pending',
    type: 'reservation',
    description: 'Deposito reserva salon social',
    residentUnit: '201',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
]

// System-wide stats
export const mockSystemStats: SystemStats = {
  totalBuildings: 5,
  activeBuildings: 4,
  totalResidents: 473,
  totalRevenue: 192000000,
  monthlyRecurringRevenue: 192000000,
  pendingPayments: 3700000,
  systemAlerts: 13,
}

// Generate parking spots for a 4x5 grid (20 visitor spots)
export const mockParkingSpots: ParkingSpot[] = [
  { id: '1', code: 'V-01', status: 'available', maxDuration: 120 },
  { id: '2', code: 'V-02', status: 'occupied', vehiclePlate: 'ABC-123', visitorName: 'Juan Perez', residentUnit: '301', entryTime: new Date(Date.now() - 45 * 60000), maxDuration: 120, timeRemaining: 75 },
  { id: '3', code: 'V-03', status: 'available', maxDuration: 120 },
  { id: '4', code: 'V-04', status: 'overtime', vehiclePlate: 'XYZ-789', visitorName: 'Maria Garcia', residentUnit: '502', entryTime: new Date(Date.now() - 150 * 60000), maxDuration: 120, timeRemaining: -30 },
  { id: '5', code: 'V-05', status: 'occupied', vehiclePlate: 'DEF-456', visitorName: 'Carlos Lopez', residentUnit: '201', entryTime: new Date(Date.now() - 30 * 60000), maxDuration: 120, timeRemaining: 90 },
  { id: '6', code: 'V-06', status: 'available', maxDuration: 120 },
  { id: '7', code: 'V-07', status: 'reserved', residentUnit: '401', maxDuration: 120 },
  { id: '8', code: 'V-08', status: 'available', maxDuration: 120 },
  { id: '9', code: 'V-09', status: 'occupied', vehiclePlate: 'GHI-321', visitorName: 'Ana Martinez', residentUnit: '103', entryTime: new Date(Date.now() - 60 * 60000), maxDuration: 120, timeRemaining: 60 },
  { id: '10', code: 'V-10', status: 'available', maxDuration: 120 },
  { id: '11', code: 'V-11', status: 'available', maxDuration: 120 },
  { id: '12', code: 'V-12', status: 'overtime', vehiclePlate: 'JKL-654', visitorName: 'Pedro Sanchez', residentUnit: '605', entryTime: new Date(Date.now() - 180 * 60000), maxDuration: 120, timeRemaining: -60 },
  { id: '13', code: 'V-13', status: 'available', maxDuration: 120 },
  { id: '14', code: 'V-14', status: 'occupied', vehiclePlate: 'MNO-987', visitorName: 'Laura Diaz', residentUnit: '402', entryTime: new Date(Date.now() - 15 * 60000), maxDuration: 120, timeRemaining: 105 },
  { id: '15', code: 'V-15', status: 'available', maxDuration: 120 },
  { id: '16', code: 'V-16', status: 'available', maxDuration: 120 },
  { id: '17', code: 'V-17', status: 'reserved', residentUnit: '204', maxDuration: 120 },
  { id: '18', code: 'V-18', status: 'available', maxDuration: 120 },
  { id: '19', code: 'V-19', status: 'available', maxDuration: 120 },
  { id: '20', code: 'V-20', status: 'occupied', vehiclePlate: 'PQR-246', visitorName: 'Sofia Ruiz', residentUnit: '701', entryTime: new Date(Date.now() - 80 * 60000), maxDuration: 120, timeRemaining: 40 },
]

export const mockVisitors: Visitor[] = [
  {
    id: '1',
    name: 'Juan Perez',
    documentId: '12345678',
    type: 'vehicle',
    vehiclePlate: 'ABC-123',
    destinationUnit: '301',
    residentName: 'Roberto Mendez',
    entryTime: new Date(Date.now() - 45 * 60000),
    status: 'inside',
    parkingSpot: 'V-02',
  },
  {
    id: '2',
    name: 'Maria Garcia',
    documentId: '87654321',
    type: 'vehicle',
    vehiclePlate: 'XYZ-789',
    destinationUnit: '502',
    residentName: 'Elena Torres',
    entryTime: new Date(Date.now() - 150 * 60000),
    status: 'inside',
    parkingSpot: 'V-04',
  },
  {
    id: '3',
    name: 'Luis Fernandez',
    documentId: '11223344',
    type: 'pedestrian',
    destinationUnit: '108',
    residentName: 'Carmen Vega',
    entryTime: new Date(Date.now() - 20 * 60000),
    status: 'inside',
  },
  {
    id: '4',
    name: 'Rosa Moreno',
    documentId: '55667788',
    type: 'pedestrian',
    destinationUnit: '305',
    residentName: 'Miguel Castro',
    entryTime: new Date(Date.now() - 120 * 60000),
    exitTime: new Date(Date.now() - 30 * 60000),
    status: 'exited',
  },
  {
    id: '5',
    name: 'Carlos Lopez',
    documentId: '99887766',
    type: 'vehicle',
    vehiclePlate: 'DEF-456',
    destinationUnit: '201',
    residentName: 'Patricia Herrera',
    entryTime: new Date(Date.now() - 30 * 60000),
    status: 'inside',
    parkingSpot: 'V-05',
  },
]

export const mockAlerts: Alert[] = [
  {
    id: '1',
    type: 'parking_overtime',
    title: 'Alerta: Parqueo en tiempo extra',
    message: 'El vehiculo XYZ-789 en el cupo V-04 ha superado el limite de 2 horas por 30 minutos. Se generara cobro al apto 502.',
    timestamp: new Date(Date.now() - 5 * 60000),
    read: false,
    priority: 'high',
    relatedId: '4',
    actionRequired: true,
  },
  {
    id: '2',
    type: 'parking_request',
    title: 'Solicitud de parqueo visitante',
    message: 'El residente del apto 401 solicita cupo de parqueadero para visitante esperado.',
    timestamp: new Date(Date.now() - 15 * 60000),
    read: false,
    priority: 'medium',
    relatedId: '7',
    actionRequired: true,
  },
  {
    id: '3',
    type: 'visitor_entry',
    title: 'Nuevo ingreso de visitante',
    message: 'Luis Fernandez (peaton) ha ingresado a visitar el apto 108.',
    timestamp: new Date(Date.now() - 20 * 60000),
    read: true,
    priority: 'low',
    relatedId: '3',
  },
  {
    id: '4',
    type: 'parking_overtime',
    title: 'Alerta critica: Tiempo extra excesivo',
    message: 'El vehiculo JKL-654 en el cupo V-12 ha superado el limite por 60 minutos. Se han enviado multiples notificaciones al apto 605.',
    timestamp: new Date(Date.now() - 2 * 60000),
    read: false,
    priority: 'critical',
    relatedId: '12',
    actionRequired: true,
  },
  {
    id: '5',
    type: 'visitor_exit',
    title: 'Salida de visitante',
    message: 'Rosa Moreno ha salido del edificio tras visitar el apto 305.',
    timestamp: new Date(Date.now() - 30 * 60000),
    read: true,
    priority: 'low',
    relatedId: '4',
  },
  {
    id: '6',
    type: 'system',
    title: 'Recordatorio de cambio de turno',
    message: 'Tu turno termina en 30 minutos. Por favor prepara el reporte de turno.',
    timestamp: new Date(Date.now() - 1 * 60000),
    read: false,
    priority: 'medium',
    actionRequired: false,
  },
]

export const mockResidents: Resident[] = [
  { id: '1', name: 'Roberto Mendez', unit: '301', phone: '+57 300 123 4567', email: 'roberto@email.com', parkingSpots: ['P-301'], balance: 0 },
  { id: '2', name: 'Elena Torres', unit: '502', phone: '+57 301 234 5678', email: 'elena@email.com', parkingSpots: ['P-502A', 'P-502B'], balance: -25000, hasRentalListing: true },
  { id: '3', name: 'Carmen Vega', unit: '108', phone: '+57 302 345 6789', email: 'carmen@email.com', parkingSpots: [], balance: 0 },
  { id: '4', name: 'Miguel Castro', unit: '305', phone: '+57 303 456 7890', email: 'miguel@email.com', parkingSpots: ['P-305'], balance: 0 },
  { id: '5', name: 'Patricia Herrera', unit: '201', phone: '+57 304 567 8901', email: 'patricia@email.com', parkingSpots: ['P-201'], balance: -15000 },
  { id: '6', name: 'Fernando Gomez', unit: '401', phone: '+57 305 678 9012', email: 'fernando@email.com', parkingSpots: ['P-401'], balance: 0, hasMarketplaceListing: true },
  { id: '7', name: 'Isabel Ramirez', unit: '605', phone: '+57 306 789 0123', email: 'isabel@email.com', parkingSpots: ['P-605'], balance: -45000 },
  {
    id: '8',
    name: 'Luis Fernandez',
    unit: '103',
    phone: '+57 307 890 1234',
    email: 'luis.fernandez@email.com',
    parkingSpots: ['P-103'],
    balance: 0,
    isTenant: true,
    tenantInfo: { ownerId: '3', ownerName: 'Carmen Vega', leaseEnd: new Date('2026-08-31') },
  },
  {
    id: '9',
    name: 'Ana Jimenez',
    unit: '405',
    phone: '+57 308 901 2345',
    email: 'ana.jimenez@email.com',
    parkingSpots: ['P-405'],
    balance: -10000,
    isTenant: true,
    tenantInfo: { ownerId: '4', ownerName: 'Miguel Castro', leaseEnd: new Date('2026-05-15') },
  },
]

export const mockTenants: Tenant[] = [
  {
    id: 'tenant-1',
    name: 'Andres Castellanos',
    documentId: '80123456',
    phone: '+57 310 111 2222',
    email: 'andres.c@email.com',
    unit: '301',
    buildingId: 'building-1',
    ownerId: 'usuario-1',
    ownerName: 'Roberto Mendez',
    ownerUnit: '301',
    leaseStart: new Date('2025-09-01'),
    leaseEnd: new Date('2026-08-31'),
    monthlyRent: 1800000,
    depositPaid: 3600000,
    status: 'active',
    vehicles: [
      {
        id: 'tv-1',
        plate: 'BCD-234',
        brand: 'Renault',
        model: 'Sandero',
        color: 'Blanco',
        parkingSpot: 'P-301',
        type: 'car',
      },
    ],
  },
  {
    id: 'tenant-2',
    name: 'Lucia Vargas',
    documentId: '52987654',
    phone: '+57 311 333 4444',
    email: 'lucia.v@email.com',
    unit: '502-B',
    buildingId: 'building-1',
    ownerId: 'usuario-2',
    ownerName: 'Elena Torres',
    ownerUnit: '502',
    leaseStart: new Date('2025-11-01'),
    leaseEnd: new Date('2026-10-31'),
    monthlyRent: 950000,
    depositPaid: 950000,
    status: 'active',
    vehicles: [],
  },
  {
    id: 'tenant-3',
    name: 'Hector Rios',
    documentId: '71456789',
    phone: '+57 312 555 6666',
    email: 'hector.r@email.com',
    unit: 'Parqueadero P-401',
    buildingId: 'building-1',
    ownerId: 'usuario-1',
    ownerName: 'Roberto Mendez',
    ownerUnit: '301',
    leaseStart: new Date('2026-01-01'),
    leaseEnd: new Date('2026-12-31'),
    monthlyRent: 180000,
    depositPaid: 180000,
    status: 'active',
    vehicles: [
      {
        id: 'tv-2',
        plate: 'EFG-567',
        brand: 'Yamaha',
        model: 'FZ',
        color: 'Negro',
        parkingSpot: 'P-401',
        type: 'motorcycle',
      },
    ],
  },
]

export const mockRentalListings: RentalListing[] = [
  {
    id: 'rental-1',
    type: 'apartment',
    ownerId: 'usuario-1',
    ownerName: 'Roberto Mendez',
    ownerUnit: '301',
    buildingId: 'building-1',
    title: 'Habitacion privada en apto 301',
    description: 'Habitacion amplia con bano privado, incluye servicios. Edificio con gimnasio y piscina. Ideal para estudiante o profesional.',
    price: 900000,
    currency: 'COP',
    period: 'monthly',
    available: true,
    availableFrom: new Date(),
    rooms: 1,
    bathrooms: 1,
    area: 18,
    amenities: ['WiFi', 'Cocina compartida', 'Lavanderia', 'Gimnasio', 'Piscina'],
    contactPhone: '+57 300 123 4567',
    status: 'active',
  },
  {
    id: 'rental-2',
    type: 'parking',
    ownerId: 'usuario-2',
    ownerName: 'Elena Torres',
    ownerUnit: '502',
    buildingId: 'building-1',
    title: 'Parqueadero P-502B disponible',
    description: 'Parqueadero cubierto segundo piso. Medidas 5x2.5m. Camaras 24/7. Acceso con tarjeta.',
    price: 180000,
    currency: 'COP',
    period: 'monthly',
    available: true,
    availableFrom: new Date(),
    parkingCode: 'P-502B',
    contactPhone: '+57 301 234 5678',
    status: 'active',
  },
  {
    id: 'rental-3',
    type: 'apartment',
    ownerId: 'usuario-2',
    ownerName: 'Elena Torres',
    ownerUnit: '502',
    buildingId: 'building-1',
    title: 'Apto 502 completo disponible en agosto',
    description: 'Apartamento de 3 habitaciones, 2 banos, balcon, 2 parqueaderos. Remodelado. Amoblado. Disponible a partir de septiembre.',
    price: 3200000,
    currency: 'COP',
    period: 'monthly',
    available: false,
    availableFrom: new Date('2026-09-01'),
    rooms: 3,
    bathrooms: 2,
    area: 95,
    amenities: ['WiFi', 'Amoblado', 'Lavadora', '2 Parqueaderos', 'Deposito', 'Gimnasio'],
    contactPhone: '+57 301 234 5678',
    status: 'paused',
  },
]

export const mockMarketplace: MarketplaceProduct[] = [
  {
    id: 'mp-1',
    sellerId: 'usuario-1',
    sellerName: 'Roberto Mendez',
    sellerUnit: '301',
    buildingId: 'building-1',
    title: 'Almuerzos caseros - Menú del dia',
    description: 'Almuerzo completo: sopa, seco con proteina, jugo y postre. Pedidos antes de las 10am. Envio al apto incluido.',
    price: 15000,
    category: 'food',
    available: true,
    contactPhone: '+57 300 123 4567',
    whatsapp: '+57 300 123 4567',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'mp-2',
    sellerId: 'usuario-2',
    sellerName: 'Elena Torres',
    sellerUnit: '502',
    buildingId: 'building-1',
    title: 'Clases de yoga - Terraza',
    description: 'Clases de yoga y meditacion en la terraza del edificio. Martes y jueves 6:30am. Grupos de max 8 personas. Precio por mes.',
    price: 80000,
    category: 'services',
    available: true,
    contactPhone: '+57 301 234 5678',
    whatsapp: '+57 301 234 5678',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'mp-3',
    sellerId: 'usuario-1',
    sellerName: 'Roberto Mendez',
    sellerUnit: '301',
    buildingId: 'building-1',
    title: 'Reparacion de computadores y celulares',
    description: 'Servicio tecnico a domicilio. Cambio de pantallas, baterias, formateo. Garantia 30 dias. Precio segun diagnostico.',
    price: 50000,
    category: 'services',
    available: true,
    contactPhone: '+57 300 123 4567',
    whatsapp: '+57 300 123 4567',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'mp-4',
    sellerId: 'usuario-2',
    sellerName: 'Elena Torres',
    sellerUnit: '502',
    buildingId: 'building-1',
    title: 'Artesanias y tejidos a mano',
    description: 'Bolsos, mantas y accesorios tejidos a crochet. Disenos exclusivos. Se aceptan pedidos personalizados.',
    price: 45000,
    category: 'crafts',
    available: true,
    contactPhone: '+57 301 234 5678',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
]

export const mockCommunications: Communication[] = [
  {
    id: 'comm-1',
    buildingId: 'building-1',
    authorId: 'admin-1',
    authorName: 'Maria Torres',
    title: 'Mantenimiento ascensor - Sabado 7 Mar',
    message: 'Estimados residentes, les informamos que el sabado 7 de marzo de 8:00am a 12:00pm se realizara mantenimiento preventivo al ascensor principal. Por favor utilizar las escaleras durante este tiempo. Pedimos disculpas por los inconvenientes.',
    type: 'maintenance',
    priority: 'high',
    targetRoles: ['usuario', 'vigilante'],
    includesTenants: true,
    sentAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    readBy: ['usuario-1'],
  },
  {
    id: 'comm-2',
    buildingId: 'building-1',
    authorId: 'admin-1',
    authorName: 'Maria Torres',
    title: 'Reunion de copropietarios - Marzo 15',
    message: 'Se convoca a asamblea ordinaria de copropietarios el proximo 15 de marzo a las 7:00pm en el salon comunal. Agenda: aprobacion presupuesto 2026, eleccion consejo de administracion, temas varios. Asistencia obligatoria o envio de poder.',
    type: 'announcement',
    priority: 'normal',
    targetRoles: ['usuario'],
    includesTenants: false,
    sentAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    readBy: ['usuario-1', 'usuario-2'],
  },
  {
    id: 'comm-3',
    buildingId: 'building-1',
    authorId: 'admin-1',
    authorName: 'Maria Torres',
    title: 'Feria de emprendimiento - Sabado 14 Mar',
    message: 'Nos complace anunciar la Primera Feria de Emprendimiento del edificio! El sabado 14 de marzo de 10am a 4pm en el salon comunal. Los residentes que tengan negocios pueden registrarse en porteria para reservar su espacio. Inviten a sus familias y amigos.',
    type: 'event',
    priority: 'normal',
    targetRoles: ['usuario', 'vigilante'],
    includesTenants: true,
    sentAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    readBy: [],
  },
  {
    id: 'comm-4',
    buildingId: 'building-1',
    authorId: 'admin-1',
    authorName: 'Maria Torres',
    title: 'URGENTE: Corte de agua - Hoy 6pm a 10pm',
    message: 'ATENCION: Por trabajos de la empresa de acueducto, esta noche de 6:00pm a 10:00pm no habra servicio de agua. Se recomienda almacenar agua para uso esencial. Disculpen los inconvenientes.',
    type: 'alert',
    priority: 'urgent',
    targetRoles: ['usuario', 'vigilante'],
    includesTenants: true,
    sentAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    readBy: [],
  },
]

export const buildingRegulations = `
# Reglamento Interno - Edificio Torres del Parque

## 1. Horarios
- Horario de recepción de paquetes: 8:00 AM - 8:00 PM
- Horario de mudanzas: Lunes a Sábado, 8:00 AM - 5:00 PM (requiere reserva previa)
- Horario de áreas comunes: 6:00 AM - 10:00 PM
- Gimnasio: 5:00 AM - 11:00 PM
- Salón social: Requiere reserva, máximo hasta 12:00 AM

## 2. Parqueadero de Visitantes
- Tiempo máximo gratuito: 2 horas
- Tarifa después de 2 horas: $5,000 COP por cada 30 minutos adicionales
- Máximo 2 visitantes por unidad al día
- Reservas: Se pueden hacer con hasta 24 horas de anticipación

## 3. Mascotas
- Se permiten mascotas de hasta 15kg
- Deben usar correa y bozal en áreas comunes
- Prohibido en piscina y gimnasio
- El propietario es responsable de recoger los desechos

## 4. Ruido
- Horario de silencio: 10:00 PM - 7:00 AM entre semana
- Fines de semana: 12:00 AM - 8:00 AM
- Obras y remodelaciones: Lunes a Viernes, 8:00 AM - 5:00 PM, Sábados hasta 1:00 PM

## 5. Áreas Comunes
- Piscina: Solo residentes y máximo 2 invitados por unidad
- BBQ: Requiere reserva con 48 horas de anticipación
- Salón de eventos: Depósito de $200,000 COP requerido

## 6. Seguridad
- Visitantes deben registrarse en portería
- Domiciliarios no suben a apartamentos (se entregan en recepción)
- Cámaras de seguridad 24/7 en áreas comunes
- Emergencias: Llamar al 123 y notificar a portería

## 7. Pagos y Multas
- Cuota de administración: Se cobra el primer día de cada mes
- Mora por atraso: 2% mensual
- Multas por infracciones: Desde $50,000 COP según gravedad
`
